### ISSUE TITLE
Docs v2: Offckb init produces an error on Windows.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/docs.nervos.org#262]
The following error is received on Windows when trying to use the command `offckb init test`:

```
C:\Users\Username\Desktop>offckb init test
? Select a Dapp template View and Transfer Balance
start cloning the dapp template..
(node:6504) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:1508
  const result = binding.readdir(
                         ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\Username\AppData\Roaming\nvm\v20.12.0\node_modules\@offckb\cli\templates\temp-clone-folder\examples\simple-transfer'
    at Object.readdirSync (node:fs:1508:26)
    at copyFolderSync (C:\Users\Username\AppData\Roaming\nvm\v20.12.0\node_modules\@offckb\cli\dist\util.js:63:22)
    at gitCloneAndDownloadFolderSync (C:\Users\Username\AppData\Roaming\nvm\v20.12.0\node_modules\@offckb\cli\dist\util.js:171:5)
    at init (C:\Users\Username\AppData\Roaming\nvm\v20.12.0\node_modules\@offckb\cli\dist\cmd\init.js:24:46)
    at C:\Users\Username\AppData\Roaming\nvm\v20.12.0\node_modules\@offckb\cli\dist\cli.js:35:28
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Username\AppData\Roaming\nvm\v20.12.0\node_modules\@offckb\cli\dist\cli.js:6:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\Username\\AppData\\Roaming\\nvm\\v20.12.0\\node_modules\\@offckb\\cli\\templates\\temp-clone-folder\\examples\\simple-transfer'
}
```

This was observed using Node v20.12.0 LTS (newest LTS via nvm) on Windows 11.

**Comment by jordanmack** [comment]
Moved to: https://github.com/RetricSu/offckb/issues/45
